### ISSUE TITLE
[이슈테스트1]재고판매량 알 수 있는 화면개발요청

### ISSUE THREAD

**Issue by oolongsawel** [oolongsawel/TIL#5]
재고판매량을 알 수 있는 화면 개발을 요청합니다

**Comment by yj-oh** [comment]
# 제 생각은 이러합니다.
- 안 : 뜨거운 부장님의 열정
- 선 : 모두들 박수
- 영 : 짝짝짝👏

**Comment by yj-oh** [comment]
> 재고판매량을 알 수 있는 화면 개발을 요청합니다

싫습니다. 일정이 되지 않습니다.

**Comment by oolongsawel** [comment]
대표님 @yj-oh  #4  5e65856 좋은커밋이었습니다
